apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo
  namespace: mydemo
  labels:
    testlabel: value
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: app
      testlabel: value
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app
        testlabel: value
    spec:
      containers:
      - name: main
        image: nginx:latest
        env:
        - name: env
          value: value
