apiVersion: apps/v1
kind: Deployment
metadata:
  name: default
  namespace: mydemo
  labels:
    test: value
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app
    spec:
      containers:
      - name: main
        image: nginx:latest
