apiVersion: v1
kind: Service
metadata:
  name: default-service
  namespace: mydemo
  labels:
    testlabel: value
spec:
  type: ClusterIP
  ports: []
  selector:
    app.kubernetes.io/name: app
    testlabel: value
