apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-demo-statefulset
  namespace: mydemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app
    spec:
      containers:
      - name: main
        image: nginx:latest
  serviceName: ""
