apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: demo-sts-v1
  namespace: mydemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app
    spec:
      containers:
      - name: main
        image: nginx:latest
        command:
        - sleep
        args:
        - "3600"
        env:
        - name: env
          value: value`
  serviceName: ""
